export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCESS = "USER_LOGIN_SUCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";

//New User Registration
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCESS = "USER_REGISTER_SUCESS";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";

//New User Details
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCESS = "USER_DETAILS_SUCESS";
export const USER_DETAILS_ERROR = "USER_DETAILS_ERROR";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

//Update Profile Details
export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCESS = "USER_UPDATE_PROFILE_SUCESS";
export const USER_UPDATE_PROFILE_ERROR = "USER_UPDATE_PROFILE_ERROR";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";
